# Generated by Django 5.1.1 on 2024-09-17 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
            ],
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название букета')),
                ('price', models.FloatField(blank=True, verbose_name='Стоимость')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event', models.ManyToManyField(related_name='events', to='flower_models.event', verbose_name='Событие')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата доставки')),
                ('status', models.CharField(choices=[('true', 'подтверждение'), ('courier', 'передан курьеру'), ('delivered', 'доставлено')], default='true', max_length=30, verbose_name='Статус')),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flower_models.bouquet')),
            ],
        ),
    ]
