# Generated by Django 5.1.1 on 2024-09-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=200, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
