# Generated by Django 5.1.1 on 2024-09-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_models', '0003_client_remove_order_full_name_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота(см)'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина(см)'),
        ),
    ]
