# Generated by Django 5.1.1 on 2024-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_models', '0004_bouquet_height_bouquet_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('true', 'подтверждение'), ('collect', 'сборка'), ('courier', 'передан курьеру'), ('delivered', 'доставлено')], default='true', max_length=30, verbose_name='Статус'),
        ),
    ]
